import Head from 'next/head'

const Meta = ({ title, description }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name='description' content={description} />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}

Meta.defaultProps = {
  title: 'NextApp',
  description: 'Generated by create next app'
}

export default Meta
